### ISSUE TITLE
libffi 源码阅读

### ISSUE THREAD

**Issue by jmpews** [jmpews/NoteZ#2]
## Prologue

libffi 动态调用 native 代码. 只要准备好 native 函数需要的参数等就可以通过 libffi 直接调用 native 函数.

说白了, libffi 实现了调用规约(Procedure Call Standard).

ARM64 的 Manual 链接: `IHI0055B_aapcs64`.

在 ARM64 的 Manual 中说明了 `Subroutine Calls` 详细的调用过程.

<h2 align="center">Somniloquy</h2>

## libffi 动态函数调用

libffi 应该算是一个 wrapper.

1. 参数准备, 这时候要根据调用规约, 填充寄存器以及栈
2. 进入 trampoline 准备调用 c 函数
3. origin_c_function 调用
4. 调用结束处理返回值

先说第一个过程参数准备过程, 即 `ffi_prep_cif_core`  函数. 这个需要判断传入所有的参数的大小, 以及返回值的类型和大小. 

## libffi closure 构建 darwin 平台下的动态桥

> waitting...

**Comment by zhangjiantao** [comment]
多数平台支持可执行内存申请的情况下，trampoline还算直观好理解，但iOS的closure实现是最神奇的，叹为观止。
首先准备了布满一个PAGE的n个trampoline
```
    .align PAGE_MAX_SHIFT
CNAME(ffi_closure_trampoline_table_page):
    .rept PAGE_MAX_SIZE / FFI_TRAMPOLINE_SIZE
    adr x16, -PAGE_MAX_SIZE
    ldp x17, x16, [x16]
    br x16
	nop		/* each entry in the trampoline config page is 2*sizeof(void*) so the trampoline itself cannot be smaller that 16 bytes */
    .endr
```
这n个大多数场景其实够用了，用完了libffi还会用vm_remap把trampoline_table克隆一页，同样具备可执行属性。所以又多出来n个。理论上是可支持动态创建无限个trampoline。

内网看到大佬的系列文章太晚了，可惜已经离职了
